### ISSUE TITLE
Bạn ơi, cho mình hỏi một chút.

### ISSUE THREAD

**Issue by nmduc2503** [Chicken-0/spm#1]
Mình đã mua route Ao (Summer Pockets Mobile) bản trên CH Play nhưng dùng bản Việt hóa thì Restore Purchased không thành công (nó báo do game không phải tải từ CH Play). Với lại, file save trên bản Việt hóa không dùng được trên bản mới hiện nay. Mong bạn bỏ chút thời gian để hỗ trợ mình. Cảm ơn bạn rất nhiều.

**Comment by Chicken-0** [comment]
Bạn tải file này: [Link](https://mega.nz/file/uRQxnaIY#60zMx7bo7BjgpsiiKakW_yNVUa5f3z7swtagD9rQV7o) 
giải nén vào folder `Android/data/jp.co.product.kn.summerpockets/files/___EXTEND_SummerPockets/`

Lưu ý: 
- Nên sao lưu lại 2 file `Gameexe.dat` và `Scene.pck` trước khi giải nén/ghi đè.
- Chạy luôn trên bản gốc của CH Play.
- Do không can thiệp vào file apk nên phần giao diện game sẽ lẫn tiếng Nhật/Anh lung tung.
- Ở màn hình chính của game sẽ không có mục chuyển qua bản REFLECTION BLUE do patch làm trên phiên bản cũ.
